brain:
  - test_brian
skill:
  - moveit
capability:
  - acml
  - map_server
  - navigation2
driver:
  - piontcloud_to_laserscan
  - ranger_ros2
  - raspi_hc_sr04
  - realsense_ros2
  - static_tf
  - unilidar_L2


